### ISSUE TITLE
Update from 3.3.0 to 3.4.5 failed with wrong scheme name

### ISSUE THREAD

**Issue by csiebert** [IteraSpeed/OpenSpeedMonitor#17]
The following error occured when upgrading from OSM 3.3.0 to OSM 3.4.5:
My db scheme name is "openspeedmonitor".
What do i have to do to fix this?

Configuring Spring Security Core ...
... finished configuring Spring Security Core

liquibase Change Set 2016-02-24-SCHEME-v341.groovy::1456401696309-1::birger (gen
erated) failed.  Error: Error executing SQL ALTER TABLE `osm`.`event_result` DRO
P FOREIGN KEY `FK3CA811623AA7BDEF`: Table 'osm.event_result' doesn't exist
liquibase.exception.DatabaseException: Error executing SQL ALTER TABLE `osm`.`ev
ent_result` DROP FOREIGN KEY `FK3CA811623AA7BDEF`: Table 'osm.event_result' does
n't exist
        at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:62)
        at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:104)
        at liquibase.database.AbstractDatabase.execute(AbstractDatabase.java:109

**Comment by nilskuhn** [comment]
Sorry for that. 

We hard coded database scheme name to the liquibase changelog. It's fixed in the HEAD and I recommend to take the HEAD. It's stable. We will package a new release the next days.

**Comment by csiebert** [comment]
Thx, it works now!
