### ISSUE TITLE
No results showing up on Graphite-Server

### ISSUE THREAD

**Issue by coderDem** [IteraSpeed/OpenSpeedMonitor#8]
Hello,

I am trying to get results on my graphite Server.
I tried the ports: 80, 22 and 2003.

What port is the right port for the use of OpenSpeedMonitor?

Best regards
codeDem

**Comment by nilskuhn** [comment]
You have to do the following, to write osm results to a graphite server:
* Create a graphite server object in osm. Here you can define URL and arbitrary port (whatever your graphite server listens to).
* Create graphite path objects in osm. They have a prefix for the graphite metric name and the osm measurand as attributes.
* You have to add the graphite paths to your graphite server in osm.
* You have to add the graphite server to a job group. For every measurand of assigned graphite paths results of given job group will than be sent to your graphite server via tcp.

_note:_ At the moment only tcp is possible. I would like to add support for udp, cause the fire and forget principle is much more robust and approppriate for sending results to graphite.

**Comment by coderDem** [comment]
Thx for the advice.
It works
